### ISSUE TITLE
The template file for gulpfile is wrong

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-dev-env#25]
Creating new project gives you errors in gulp file:
`gulp -T`:
```
Error: Cannot find module 'ckeditor5-dev-lint'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
```

The problem is with package ckedito5-dev-lint which should be required as below:
```js
const ckeditor5Lint = require( '@ckeditor/ckeditor5-dev-lint' )( config );
```

**Comment by Reinmar** [comment]
And `package.json` is also wrong.
